### ISSUE TITLE
uitleining partner logos

### ISSUE THREAD

**Issue by lfb0801** [salvemundi/salvemundi.nl-laravel#27]
Het Logo van Fontys overlapt het logo van Hubble.

<details>
<summary>Voorbeeld</summary>

![image](https://user-images.githubusercontent.com/16375630/112394427-009f8180-8cfd-11eb-8d9c-c620cccd05a2.png)
</details>

**Comment by lfb0801** [comment]
Is dit onderhand niet opgelost?

**Comment by iqfx** [comment]
Ik ben hier  mee bezig geweest en het is al beter maar nog niet helemaal zoals ik het wil. Ik close het issue wanneer het werkt.
