### ISSUE TITLE
Pagina voor bijbanen bank

### ISSUE THREAD

**Issue by TjerkvGerwen** [salvemundi/salvemundi.nl-laravel#31]
Plek waar een bericht geplaatst kan worden wat bestaat uit

- Bedrijfsnaam
- Uurtarief
- Uren
- Omschrijving bijbaan
- Knop om meer informatie aan te vragen bij bijbanenbank@salvemundi.nl (email adres moet nog gemaakt worden)

**Comment by Albion99** [comment]
Fixed it
