### ISSUE TITLE
Afbeeldingen van gebruikers worden niet in de browser-cache opgeslagen

### ISSUE THREAD

**Issue by MaxKorlaar** [salvemundi/salvemundi.nl-laravel#33]
Ondanks dat Cloudflare als CDN wordt gebruikt, worden de afbeeldingen ook daar niet gecachet. De afbeeldingen hebben geen bestandsnaamextensie in de naam (https://salvemundi.nl/storage/users/xxxxxxx) en er zit geen Cache-Control header op de response. De enige reden dat de cache-control headers wel op de meeste afbeeldingen zitten, is omdat Cloudflare deze toevoegt, niet omdat dit is geconfigureerd op de webserver. Dit probleem lijkt zich in ieder geval voor te doen voor afbeeldingen geüpload vanaf de website zelf.

Overigens raad ik het ook sterk aan om te kijken naar een verdeling van de commissies over eigen pagina's. Hierdoor wordt het mogelijk om meer tekst en leden bij commissies weer te geven zonder dat de pagina daardoor onoverzichtelijk druk wordt in zijn geheel. Ook is het dan niet nodig voor de browser, vooral op mobiele verbindingen, om _alle_ foto's van alle commissieleden te laden.

**Comment by iqfx** [comment]
Caching wordt gehandled door cloudflare.
