### ISSUE TITLE
Remove inactive users

### ISSUE THREAD

**Issue by TjerkvGerwen** [salvemundi/salvemundi.nl-laravel#37]
Hi,

Het zou top zijn als er na 1 juni een funtie is die automatisch niet betaalde leden office accounts disabled na 1 maand en dat deze office accounts na 6 maanden niet betaald te hebben automatisch worden verwijderd.

t zou ook tof zijn om de disabled users in te zien in de leden administratie

**Comment by iqfx** [comment]
oh dat kan ez, will add.
