### ISSUE TITLE
Make 'Bijbanen bank' cards more responsive

### ISSUE THREAD

**Issue by davydehaas98** [salvemundi/salvemundi.nl-laravel#92]
The cards in 'Bijbanen bank' should be as responsive as, for example, the clubs page.
The page should have little margin on the sides to make the cards easily readable.

The css creating this issue:

.cardNews
width: 50%

It should be a bigger percentage, something like 80%. (Or in pixels)

**Comment by iqfx** [comment]
Fixed in #101
